### ISSUE TITLE
use this ext in this ext

### ISSUE THREAD

**Issue by hooman-pro** [kop/yii2-scroll-pager#41] opened 2015-10-12 15:21 UTC
hi i try to load this widget inside of view file for my post and comments 
post:

```php
<?= ListView::widget([
        'dataProvider' => $dataProvider,
        'id'=>'posts',
        'itemOptions' => ['class' => 'item'],
        'itemView' => '_view',
        'summary'=>'',
        'pager' => [
            'class' => \kop\y2sp\ScrollPager::className(),
            'triggerText' => 'Load More news',
            'triggerOffset' => 2000,
            'noneLeftText' => 'انتهای صفحه',
            'enabledExtensions'=>[
                kop\y2sp\ScrollPager::EXTENSION_TRIGGER,
                kop\y2sp\ScrollPager::EXTENSION_SPINNER,
                kop\y2sp\ScrollPager::EXTENSION_NONE_LEFT,
                kop\y2sp\ScrollPager::EXTENSION_PAGING,
            ]
        ],
    ]) ?>
```

comments: in the  'itemView' => '_view' file

```php
<?= ListView::widget([
                    'dataProvider' => $model->getCommentsDataProvider(),
                    'id'=>'comments'.$model->id,
                    'itemOptions' => ['class' => 'comments_items'.$model->id],
                    'itemView' => '/comment/_view',
                    'summary'=>'',
                    'pager' => [
                        'id'=>'comments'.$model->id,
                        'class' => \kop\y2sp\ScrollPager::className(),
                        'triggerText' => 'نمایش بیشتر',
                        'triggerOffset' => 0,
                        'noneLeftText' => '',
                        'enabledExtensions'=>[
                            kop\y2sp\ScrollPager::EXTENSION_TRIGGER,
                            kop\y2sp\ScrollPager::EXTENSION_SPINNER,
                            kop\y2sp\ScrollPager::EXTENSION_NONE_LEFT,
                            kop\y2sp\ScrollPager::EXTENSION_PAGING,
                        ],
                        //'eventOnPageChange'=>'function(){alert("fds");}'
                        //'eventOnLoad'=> 'function(){alert("sda");}',
                    ],
                ]) ?>
```
but it set the second one config for first one and dont show load more button

**Comment by kop** [comment] 2015-10-14 15:56
I'm not really sure about this one. But try to update ListView widget in your comments file and set different ID's for ListView and pager widgets. Cause right now both your listview and pagers have the same `'comments'.$model->id` ID.

**Comment by kop** [comment] 2016-03-29 02:59
Is a duplicate of #20.

**Closed by kop** 2016-03-29 02:59 UTC
Labels: bug, duplicate
