### ISSUE TITLE
Scroll down then hit refresh. Page stays on ?page=4&per-page=5

### ISSUE THREAD

**Issue by nsanden** [kop/yii2-scroll-pager#45] opened 2015-10-31 22:53 UTC

**Comment by masiha68** [comment] 2015-12-22 18:15
hi ... i have this isuue ... how i can fixed

**Comment by nibinpaul** [comment] 2016-03-08 06:31
i have same problem.

**Comment by masiha68** [comment] 2016-03-08 07:03
remove history extension

   public $enabledExtensions = [
        self::EXTENSION_TRIGGER,
        self::EXTENSION_SPINNER,
        self::EXTENSION_NONE_LEFT,
        self::EXTENSION_PAGING,
       // self::EXTENSION_HISTORY
    ];

**Comment by nibinpaul** [comment] 2016-03-10 17:54
Thank you @masiha68 .
it works.

**Comment by kop** [comment] 2016-03-29 00:44
This is duplicate of #40.

**Closed by kop** 2016-03-29 00:44 UTC
Labels: duplicate

**Comment by bilginnet** [comment] 2017-12-05 12:41
I need to changing address bar after scroll. 
if i disabled HISTORY address bar does not changing. 
if i enabled HISTORY address bar changing but previos data does not showing.
How can i fix this ?
